### ISSUE TITLE
The advantage over traditional drone-basedd 3D reconstruction

### ISSUE THREAD

**Issue by derrick-xwp** [InternLandMark/LandMark#7]
Dear author,

I am wondering about the advantage of NeRF-based city-scale reconstruction over drone-based methods.

Thanks!

**Comment by kam1107** [comment]
Hi. By saying 'drone-based' methods, I assume you mean photogrammetry? In that case, NeRF is advantageous in multiple aspects, for example:
- More robust: NeRF models can accommodate varying lighting conditions and scene dynamics but photogrammetry is highly likely to fail in these cases
- More continuous: sometimes lack of views can cause holes in the mesh results constructed by photogrammetry, but NeRFs outputs more continuous results due to its inductive bias and the ability to reason about spatial coordinated
- Easier on memory: NeRFs encode the scene into a light-weight MLP and can unify varying LOD into one model, compared to meshes which are usually heavier on memory and requires mipmap or a pyramid of meshes to represent **limited** LOD
-  Better rendering quality: sometime photogrammetry gives distorted texture surface caused by view inconsistency and lack of multi-views. NeRF on the other hand, is trained end2end with reconstruction loss, so its rendering quality is more reliable.

Hope this helps!
